# Generated by Django 4.2.1 on 2023-05-31 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('status', models.CharField(max_length=20)),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('about', models.TextField()),
                ('images', models.ImageField(upload_to='car_images/')),
                ('rating', models.FloatField()),
                ('other', models.TextField()),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.status')),
            ],
        ),
    ]
