# Generated by Django 4.2.1 on 2023-05-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('info', models.TextField()),
                ('images', models.ImageField(upload_to='car_images/')),
                ('status', models.CharField(max_length=20)),
                ('rating', models.FloatField()),
                ('other', models.TextField()),
            ],
        ),
    ]
