# Generated by Django 4.2.1 on 2023-06-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_cars_options_alter_status_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Published'),
        ),
    ]
